name: CI

on: [push, pull_request]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.4.0
    - uses: docker/setup-qemu-action@v2.1.0
    - uses: docker/setup-buildx-action@v2.5.0
    - uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # ensure that Docker image can be built from Dockerfile
    - uses: docker/build-push-action@v4.0.0
      with:
        tags: tiddlywiki5 # irrelevant
    - uses: docker/build-push-action@v4.0.0
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/henry40408/tiddlywiki5:nightly
      if: github.ref_type == 'branch' && github.ref_name == 'main'
    - uses: docker/build-push-action@v4.0.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: "ghcr.io/henry40408/tiddlywiki5:${{ github.ref_name }}"
      if: github.ref_type == 'tag'
    - uses: docker/build-push-action@v4.0.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/henry40408/tiddlywiki5:latest
      if: github.ref_type == 'tag'
